priority: high
usepermissions: true
verbosity: normal
ticks: 40
safeinsideboundary: false

boundaries:
  main_boundary:
    radius: 200
    centre-x: 0
    centre-z: 0
    world: ALL
    damage: 0
    except: [Xsarqn, player2]
    exceptpermissions: [mainBoundaryOverride]  # give players otherbounds.custom.mainBoundaryOverride (note, cannot include _ characters)
    messagedanger: Warning - high radiation level detected.
    messagesafe: You have returned to safer lands.


  second_boundary:
    radius: 210
    center-x: 0
    center-z: 0
    world: ALL
    damage: 1
    except: [Xsarqn, player2]
    exceptpermissions: [second_boundary_override]  # give players otherbounds.custom.main_boundary_override
    messagedanger: 2-Warning - high radiation level detected.
    messagesafe: 2-You have returned to safer lands.

